[build]
  command = "solid-start build"
  functions = "netlify/functions"
  publish = "netlify"

[[plugins]] 
  package = "netlify-plugin-cypress"

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
